openapi: '3.0.2'
info:
  title: CHAT REST API
  description: REST API endpoints for managing the chat's related resources
  version: '0.0.0'
servers:
  - url: "http"
paths:
  /user/all:
     get:
      tags:
        - User
      summary: Fetch all user
      description: Fetch users
      operationId: getAllUser
      security:
        - oAuth:
            - user:read
      parameters:
        - name: fieldsToExtractCode
          in: query
          required: true
          schema:
            type: string
          description: specify the fields that will be present the response
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/UserDTO'